.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "STAGE\-CLEAN\-SMARTDC" "1" "March 2013" "" ""
.
.SH "NAME"
\fBstage-clean-smartdc\fR \-\- Stops and deletes all your SmartDC machines
.
.SH "SYNOPSIS"
.
.nf
stage\-clean\-smartdc [options]
.
.fi
.
.SH "DESCRIPTION"
Cleans (stops and deletes) your SmartDC machine pool\. This command stops and deletes \fBall\fR available machines, so use with caution\.
.
.SH "OPTIONS"
Available options for command:
.
.IP "\(bu" 4
\fB\-v\fR, \fB\-\-version\fR:
.
.br
Shows current version of the command, then exit
.
.IP "\(bu" 4
\fB\-\-help\fR:
.
.br
Shows the manual page entry for command
.
.IP "\(bu" 4
\fB\-\-usage\fR:
.
.br
Show command usage, then exit
.
.IP "\(bu" 4
\fB\-\-quiet\fR:
.
.br
Do not print any information\.
.
.IP "\(bu" 4
\fB\-\-silent\fR:
.
.br
See \fI\-\-quiet\fR
.
.IP "\(bu" 4
\fB\-\-debug\fR:
.
.br
More verbose output
.
.IP "\(bu" 4
\fB\-\-ignore\-confirm\fR:
.
.br
Do not show the confirm prompt (run command without confirmation)\.
.
.IP "\(bu" 4
\fB\-\-no\-of\-attempts <number>\fR:
.
.br
Number of stop/delete attempts per machine\. Default=5
.
.IP "\(bu" 4
\fB\-\-sdcurl <url>\fR:
.
.br
The \fIURL\fR for the Joyent API (e\.g\. https://us\-sw\-1\.api\.joyentcloud\.com/)
.
.IP "\(bu" 4
\fB\-\-account <account>\fR:
.
.br
Joyent account name
.
.IP "\(bu" 4
\fB\-\-keyid <keyid>\fR:
.
.br
Key name of the SSH/RSA Key associated with your Joyent account
.
.IP "" 0
.
.SH "EXAMPLES"
Deletes all machines without confirmation:
.
.IP "" 4
.
.nf
stage\-clean\-smartdc \-\-ignore\-confirm
.
.fi
.
.IP "" 0
.
.SH "ENVIRONMENT VARIABLES"
The following enivornment variables are used by command:
.
.P
  \fISDC_URL\fR
.
.br
  The \fIURL\fR for the Joyent API (e\.g\. https://us\-sw\-1\.api\.joyentcloud\.com/)
.
.P
  \fISDC_ACCOUNT\fR
.
.br
  Joyent account name
.
.P
  \fISDC_KEY_ID\fR
.
.br
  Key name of the SSH/RSA Key associated with your Joyent account
.
.SH "COPYRIGHT"
Copyright (C) 2013 Johan Dahlberg \fIhttp://jfd\.github\.com\fR
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
stage(1)
.
.IP "\(bu" 4
stage\-setup\-machine(1)
.
.IP "\(bu" 4
stage\-setup\-smartdc(1)
.
.IP "" 0

