.\" Generated with Ronnjs 0.3.8
.\" http://github.com/kapouer/ronnjs/
.
.TH "STAGE\-SLAVE" "1" "January 2013" "" ""
.
.SH "NAME"
\fBstage-slave\fR \-\- Spawn Slave
.
.SH "SYNOPSIS"
.
.nf
stage\-slave [options]
.
.fi
.
.SH "DESCRIPTION"
Spawns a new Stage Slave Server process\.
.
.SH "OPTIONS"
Available options for command:
.
.IP "\(bu" 4
\fB\-v\fR, \fB\-\-version\fR:
.
.br
Shows current version of the command, then exit
.
.IP "\(bu" 4
\fB\-\-help\fR:
.
.br
Shows the manual page entry for command
.
.IP "\(bu" 4
\fB\-\-usage\fR:
.
.br
Show command usage, then exit
.
.IP "\(bu" 4
\fB\-\-url <url>\fR:
.
.br
Full \fIurl\fR where to the Stage Master Server\. This can also be controlled by setting the STAGE_URL environment variable\.
.
.IP "\(bu" 4
\fB\-\-host <host>\fR:
.
.br
Set the \fIhost\fR of current \fIurl\fR to the Stage Master Server\.
.
.IP "\(bu" 4
\fB\-\-port <port\fR:
.
.br
Set the \fIport\fR of current \fIurl\fR to the Stage Master Server\.
.
.IP "\(bu" 4
\fB\-\-secure\fR:
.
.br
Indicates that the \fIurl\fR to the Stage Master Server is secure\. The protocol of the \fIurl\fR is changed to \fIhttps\fR
.
.IP "\(bu" 4
\fB\-\-token <token>\fR:
.
.br
Sends the required \fItoken\fR requested by the Stage Master Server\.
.
.IP "\(bu" 4
\fB\-\-cachepath <path>\fR:
.
.br
Path where test packages should be stored\. Default to \fIcache\fR in current workdir\.
.
.IP "\(bu" 4
\fB\-\-loglevel <silent|fatal|warn|info|verb|debug>\fR:
.
.br
Log level\. Defaults to \fIwarn\fR\|\.
.
.IP "\(bu" 4
\fB\-\-signal <SIGUSR1|SIGUSR2>\fR:
.
.br
Signal used to communicate with tests\.
.
.IP "\(bu" 4
\fB\-\-forkmode\fR:
.
.br
Starts process in \fBforkmode\fR\|\. Sends a \fB{ url: <url> }\fR\-message to parent process, each time connected to the Master process\.
.
.IP "" 0
.
.SH "EXAMPLES"
Spawns a new Slave Server that connects to a running Master Server on 127\.0\.0\.1:9000:
.
.IP "" 4
.
.nf
stage\-slave \-\-url 127\.0\.0\.1:9000
.
.fi
.
.IP "" 0
.
.SH "ENVIRONMENT VARIABLES"
The following enivornment variables are used by command:
.
.P
  \fISTAGE_URL\fR
.
.br
  The full URL to the Stage Master Server e\.g \fBhttp://myserver:8080/\fR\|\.
.
.SH "COPYRIGHT"
Copyright (C) 2013 Johan Dahlberg \fIhttp://jfd\.github\.com\fR
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
stage(1)
.
.IP "\(bu" 4
stage\-master(1)
.
.IP "\(bu" 4
stage\-localenv(1)
.
.IP "" 0

